author: xbfighting # 作者
description: xbfighting's blog
keyword: full-stack, C#, mac
favicon: 

excerpt_link: Read more

menu:
 Home: /
#  Tags: /tags/
 Archives: /archives/
 Projects: /project/ 
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment or uyan

comment: gitment

# gitment config
gitment_owner: xbfighting
gitment_repo: xbfighting.github.io
gitment_oauth_id: 136da4d3a4315c504bce
gitment_oauth_secret: 9b8f176696ab10b3fd70fe50898f3d254e6dd221

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://avatars3.githubusercontent.com/u/4010328
  description: "Luck is what happens when praparation meet opportunity."
  weibo_username: thisboyneedagirl
  twitter_username: WhiteKing5120
  github_username: xbfighting
  zhihu_username: bai-lei-cheng


# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
